
export const DRACULOR_STATS = {
  HP: 300000, // 25k -> 300k
  DAMAGE_MELEE: 250,
  SPEED_BASE: 0.18, 
  SPEED_PHASE: 0.35,
  PHASE_THRESHOLDS: [0.75, 0.50, 0.25]
};

export const ABILITIES = {
  BAT_INFERNO: 'BAT_INFERNO',
  BLOOD_RAIN: 'BLOOD_RAIN',
  VAMPIRIC_GRASP: 'VAMPIRIC_GRASP',
  PHASE_FURY: 'PHASE_FURY'
};
