
export const PAPAMAMA_STATS = {
  HP: 2500000, // Massive HP
  DAMAGE: 400,
  SPEED: 0.09,
  PHASE_THRESHOLDS: [0.50]
};

export const ABILITIES = {
  DUAL_BREATH: 'DUAL_BREATH',
  MAGMA_ERUPTION: 'MAGMA_ERUPTION',
  PHASE_ROAR: 'PHASE_ROAR',
  TAIL_SWIPE: 'TAIL_SWIPE'
};
