
export const FALLEN_ANGEL_STATS = {
  HP: 1000000, // 1 Million HP base
  DAMAGE: 150,
  SPEED_BASE: 0.07, 
  SPEED_PHASE_2: 0.11,
  PHASE_THRESHOLDS: [0.50] 
};

export const ABILITIES = {
  PURIFYING_NOVA: 'PURIFYING_NOVA',
  RESURRECTION: 'RESURRECTION',
  WING_SHIELD: 'WING_SHIELD',
  SMITE_BEAM: 'SMITE_BEAM',
  FALLEN_METEOR: 'FALLEN_METEOR'
};
