
export const SOVEREIGN_STATS = {
  HP: 450000, 
  DAMAGE_VOID: 300,
  PHASE_THRESHOLDS: [0.50]
};

export const ABILITIES = {
  MEGA_TETHER: 'MEGA_TETHER',
  PORTAL_RIFT: 'PORTAL_RIFT',
  BLACK_HOLE: 'BLACK_HOLE'
};
