
export const HARVESTER_STATS = {
  HP: 750000,
  DAMAGE_MELEE: 400,
  SPEED: 0.06, 
  PHASE_THRESHOLDS: [0.50]
};

export const ABILITIES = {
  SCYTHE_REAP: 'SCYTHE_REAP',
  MEAT_TENDRILS: 'MEAT_TENDRILS',
  HARVEST_PULL: 'HARVEST_PULL'
};
